version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: django_demo.app
    entrypoint: "/app/django_demo/docker-entrypoint.sh"
    image: clintonb/django_demo:latest
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - logs:/logs
      - media:/public/media/
      - static:/public/static/
  web:
    container_name: django_demo.web
    image: nginx:1.15-alpine
    links:
      - app
    ports:
      - 8080:80
    restart: always
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - logs:/var/log/nginx
      - media:/public/media:ro
      - static:/public/static:ro
volumes:
  logs:
  media:
  static:
